### ISSUE TITLE
Organization system

### ISSUE THREAD

**Issue by riderx** [Cap-go/capgo#258]
Instead of link app to user, we want to create org for user and link app to org.
That will allow us to give org right to more than one user.

**Comment by riderx** [comment]
Current status:
- org model have been added in the DB
- org user role have been added in the DB
- default org are created for every new user who register
- one org by user has been created for previous users
- admin user's rights have been granted to all org owners
- channel users have been copied as org right
- Figma for frontend has been drafted: https://www.figma.com/proto/18gJfn8NiwEMxSosZzX2G7/Capgo-Organisation?page-id=0%3A1&type=design&node-id=38-81&viewport=4233%2C229%2C0.51&t=Uz41DeV2hkH37JFj-1&scaling=min-zoom&starting-point-node-id=38%3A81&mode=design

**Comment by riderx** [comment]
To do: 
- Finish Figma design
- Implement Figma in frontend
- display org
- allow creating delete or edit your org in front
- display org users
- allow adding delete org users in front
- allow update org users right in front
- add feature to add user to org in front
- add security rule in new tables, org, and org rights
- create a Postgres function to check user rights for org
- create a Postgres function to check user rights for app
- create a Postgres function to check user rights for channel
- transfer apps to org
- update security rules to use new org rights
- transfer billing info from user to org
- display org billing
- ...

**Comment by YacineMessaadi** [comment]
- [ X ]  Finish Figma Design
=> Desktop : [click here](https://www.figma.com/proto/18gJfn8NiwEMxSosZzX2G7/Capgo-Organisation?page-id=0%3A1&type=design&node-id=38-81&viewport=1274%2C415%2C0.31&t=3GKnOtAxieWGO77b-1&scaling=min-zoom&starting-point-node-id=38%3A81&show-proto-sidebar=1&mode=design)
=> Mobile : [click here](https://www.figma.com/proto/18gJfn8NiwEMxSosZzX2G7/Capgo-Organisation?page-id=106%3A35&type=design&node-id=106-269&viewport=6230%2C195%2C0.68&t=zoqdwuws9D2FzwZR-1&scaling=min-zoom&starting-point-node-id=106%3A269&mode=design)

**Comment by riderx** [comment]
@YacineMessaadi thanks for the work.
Some remarks though :
- the current style of tabs don’t match the one in figma, i would prefer we follow the same as we have already.
- Org will have logo as well to edit and should have the same design as current setting screen
- I don’t see the edit user
- Apikey need to have action: delete recreate, added 
- image in add new member don’t match the current style of the app
- Org selector miss org logo
- Org selector is missing the color scheme of the app, should be white on white app dark on dark app

**Comment by YacineMessaadi** [comment]
@riderx 

DONE: the current style of tabs don’t match the one in figma, i would prefer we follow the same as we have already.
DONE: Org will have logo as well to edit and should have the same design as current setting screen
DONE: I don’t see the edit user (click on three dots on an example member)
DONE: Apikey need to have action: delete recreate, added
DONE: image in add new member don’t match the current style of the app (deleted the image)
MISSING: Org selector miss org logo (I encounter a difficulty in the modification of the plugin I use for the selector but it will be done in the code)
PARTIALLY: Org selector is missing the color scheme of the app, should be white on white app dark on dark app (same reason as before)

**Comment by riderx** [comment]
Still missing:
- add apikey mobile ( big plus button like for apps)
- tabs mobile design still don't match the current design
- copy button is not necessary since you can click the key, in apikeys
- still no UI to edit user rights
- replace on left panel the api keys button by organisation to access to the new pannel. ( the top selector should keep the page you are (dashboard/org setting apikey etc)

**Comment by riderx** [comment]
Done:
- create a Postgres function to check user rights for org
- create a Postgres function to check user rights for app
- create a Postgres function to check user rights for channel
By this function :
```sql
CREATE OR REPLACE FUNCTION check_min_rights(min_right user_min_right, user_id uuid, org_id uuid, app_id varchar, channel_id bigint)
RETURNS boolean AS $$
DECLARE
    user_right_record RECORD;
BEGIN
    FOR user_right_record IN 
        SELECT org_users.user_right, org_users.app_id, org_users.channel_id 
        FROM org_users 
        WHERE org_users.org_id = check_min_rights.org_id AND org_users.user_id = check_min_rights.user_id
    LOOP
        IF (user_right_record.user_right >= min_right AND user_right_record.app_id IS NULL AND user_right_record.channel_id IS NULL) OR
           (user_right_record.user_right >= min_right AND user_right_record.app_id = check_min_rights.app_id AND user_right_record.channel_id IS NULL) OR
           (user_right_record.user_right >= min_right AND user_right_record.app_id = check_min_rights.app_id AND user_right_record.channel_id = check_min_rights.channel_id)
        THEN
            RETURN true;
        END IF;
    END LOOP;

    RETURN false;
END;
$$ LANGUAGE plpgsql;
```

**Comment by riderx** [comment]
@YacineMessaadi I think we also need views in Figma from different rights.
- read
- upload
- write
- admin
And for different level:
- channel
- app
- org

What user with this rights see is important.

**Comment by YacineMessaadi** [comment]
- DONE: add apikey mobile ( big plus button like for apps)
- NEED INFO (The current design is icon + title in Capgo, should I delete the title ?) : tabs mobile design still don't match the current design ( only icon + underline tabs)
- DONE: copy button is not necessary since you can click the key, in apikeys
- DONE (click the three dots on the member Ivan Mesaros) : still no UI to edit user rights
- NEED INFO (The top selector should be clickable to navigate through the pages of the org ? (settings, api keys, members) ?) : replace on left panel the api keys button by organisation to access to the new pannel. ( the top selector should keep the page you are (dashboard/org setting apikey etc)

**Comment by YacineMessaadi** [comment]
> @YacineMessaadi I think we also need views in Figma from different rights.
> 
> * read
> * upload
> * write
> * admin
>   And for different level:
> * channel
> * app
> * org
> 
> What user with this rights see is important.

@riderx 
I agree, but I think it will be a waste of time to go deep in details on the Figma design.
Actually, that would take time that we had not planned on the schedule for the feature delivery

**Comment by pbkompasz** [comment]
@riderx 
Hi. I have a couple of questions:
1) Is this the final version of the Figma draft? Will the views with different permissions be created in Figma?
2) When I try to start the database I get migration errors, should this happen or am I missing something? Please let me know if I am missing some build steps.

**Comment by riderx** [comment]
The fig la still lack of some view as I shared, you are free to design them or propose a design template from any open source tailwind component

**Comment by pbkompasz** [comment]
Ok, now I have a clearer picture. I will start working tomorrow and let you know if I have any questions.

**Comment by riderx** [comment]
@pbkompasz any updates ?
I updated the seeds sql to make it work in local to help you test

**Comment by pbkompasz** [comment]
@riderx I saw the commits. I started with the frontend and made some progress but I didn't have much free time this week. I will try to finish it by Saturday.

**Comment by pbkompasz** [comment]
@riderx The billings menu should redirect to a Stripe dashboard like in the user settings?

**Comment by pbkompasz** [comment]
@riderx Can you give some more information on the organization rights. And also the security rules e.g. a member with a right what actions can perform.

**Comment by riderx** [comment]
I let you do a proposal of what they can access

**Comment by neo773** [comment]
/attempt #258 @pbkompasz I'll take it over from here

**Comment by WcaleNieWolny** [comment]
Since neo cancelled his attempt 12 hours ago, I will be taking this. Do we want to replace all `user_id` to `org_id`?

If so, how do we go about migration? Do I just write some SQL to migrate from old user_id into org_id and when we merge this system we turn off prod -> migrate -> restart prod?

**Comment by WcaleNieWolny** [comment]
I redesigned the members panel as I did not liked how it looked.
@riderx  can you please give me some feedback on this?

![image](https://github.com/Cap-go/capgo/assets/50914789/b5283b8a-6e59-46e2-8956-c84bda614f5c)

Do you like how this looks or no?

**Comment by riderx** [comment]
Im good with it

**Comment by WcaleNieWolny** [comment]
Wrote a dialog to insert email of the user that we want to invite. Please give feedback on this @riderx 

![image](https://github.com/Cap-go/capgo/assets/50914789/57f0fb93-2051-47a1-bbd7-aab3024bef49)

**Comment by WcaleNieWolny** [comment]
I will probably replace the `Invite` button with some sort of `next` button that will trigger another dialog asking of what type of permission do you want to give the user

**Comment by WcaleNieWolny** [comment]
Here is a demo for the invitation system (Only for organizations for now)
I used a SQL fn  and not a new edge fn to implement this
Please let me know if you like it @riderx 

https://github.com/Cap-go/capgo/assets/50914789/e8ab0c79-eb8d-4832-b8e5-95511bc3fde1

**Comment by WcaleNieWolny** [comment]
As for API keys:

I will keep them per user and not per org. It is really pointless to have shared api keys per org and having api keys per org add unnecessary complexity

**Comment by riderx** [comment]
@WcaleNieWolny for the Dialog did you made the same as we have now for channel invite, if user don't exist it invite him, and ask for name as well
Otherwise nice, why 2 modals ?
Nice, there are no edge function !
For APIKEY the point was to have as user a different apikey in each org not shared one.
But that ok for now to have them by users

**Comment by WcaleNieWolny** [comment]
> why 2 modals

I though it looked more "clean" that way, the first modal is strictly for email and the other one if for permissions with a nice explanation. Sure, I could pack that into one but then we would not have a nice explanation for each of the button.

Used 2 modals to make the UX better

**Comment by riderx** [comment]
I mean this invite system is not linked to channel, it's more about if the user doesn't exist in Capgo we have a way to create him and send a magic link with Supabase.
So when you set Tony Cooley it means the user will have already Tony Cooley in his account it will just arrive at the step set password.
You can try this in the prod by going to channel of one app and try to invite one of your other email

**Comment by WcaleNieWolny** [comment]
Wrote some code to accept invitations, please let me know if you like it @riderx 

https://github.com/Cap-go/capgo/assets/50914789/edc72f60-c8d2-4291-9e4c-ef579eb0a2ac

**Comment by WcaleNieWolny** [comment]
> transfer billing info from user to org
I do not like this idea. I strongly believe that billing should stay as is and if you are invited to any valid (billed) org then you can use capgo. Transferring billing to org adds extra complexity that could be avoided. Any org admin will not be paying for the org with his own money. That is the job of the owner

**Comment by neo773** [comment]
@zcesur
Can you fix this edge case where the bot reminds you of bounty being up for grabs even though you've canceled the attempt a while ago.

**Comment by zcesur** [comment]
@neo773 sorry about that - I'm on it
